CREATE TABLE INFLUENCE_ORDERS
(ID INTEGER PRIMARY KEY AUTOINCREMENT,
 GAME VARCHAR(50),
 USER VARCHAR(50),
 TURN VARCHAR(10),
 NATION VARCHAR(50),
 COMMAND VARCHAR(50),
 TARGET VARCHAR(50),
 EXEC_ORDER INTEGER);
