CREATE TABLE BOP_BOT_ACTIONS
(ID INTEGER PRIMARY KEY AUTOINCREMENT,
 GAME VARCHAR(100),
 BOT INTEGER,
 ACTION VARCHAR(100),
 PARAM1 VARCHAR(100),
 PARAM2 VARCHAR(100),
 PARAM3 VARCHAR(50),
 PARAM4 VARCHAR(50),
 PARAM5 VARCHAR(50),
 START_TURN VARCHAR(10),
 START_TIME TIMESTAMP
);
